services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=mySuperSecretKey123!
      - PORT=3001
      - DB_PATH=./database.sqlite
    volumes:
      - backend_data:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data:
